name: Update latexdiff pdf (intro.tex)

on:
  push:
    branches:
    - main
    paths:
    - intro.tex

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install latexdiff
      run: |
        curl -o latexdiff.zip http://ctan.imsc.res.in/support/latexdiff.zip
        unzip latexdiff.zip
        cd latexdiff
        sudo make install
    - name: Save commits into files
      run: |
        
        git log -n 1 --pretty=format:"%H" main intro.tex | xargs -I{} git show {}:intro.tex > new.tex
        git log -n 1 --skip 1 --pretty=format:"%H" main intro.tex | xargs -I{} git show {}:intro.tex > old.tex
    - name: Run latexdiff on files
      run: |
        latexdiff old.tex new.tex > diff.tex
        latexdiff-vc 
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        delete-branch: true
        branch-suffix: short-commit-hash
        commit-message: update pdf
        title: Update pdf
        body: |
            Update pdf
