# Add new file with location under `paths` and `file-path`
# Replace every `main` with the branch name (use find and replace all for convenience)

name: Update latexdiff pdf

on:
  push:
    branches:
    - main
#    paths:
#    - intro.tex
#    - folder1/test.tex

jobs:
  latexdiff:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file-path: [intro.tex, folder1/test.tex]

    steps:
    - name: latexdiff for ${{ matrix.file-path }}
      uses: actions/checkout@v2
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add \*.pdf
        git commit -m "Update ${{ matrix.file-path }} pdf"
        git push

      # Install latexdiff
    - name: Install latexdiff
      run: |
        curl -o latexdiff.zip http://ctan.imsc.res.in/support/latexdiff.zip
        unzip latexdiff.zip
        cd latexdiff
        sudo make install
        cd ..

      # Save second latest commit as old.tex
    - name: Save commit into a file
      run: |
        ls -a
        git log -n 1 --skip 1 --pretty=format:"%H" main ${{ matrix.file-path }} | xargs -I{} git show {}:${{ matrix.file-path }} > old.tex
        cat old.tex

      # Run latexdiff on old.tex and new.tex and save it as pdf
    - name: Run latexdiff
      run: |
        yes "" | latexdiff-vc --pdf old.tex ${{ matrix.file-path }}

#      # Push the pdf
#    - uses: actions/checkout@v2
#    - run: |
#        git config user.name github-actions
#        git config user.email github-actions@github.com
#        git add \*.pdf
#        git commit -m "Update ${{ matrix.file-path }} pdf"
#        git push
