# Add new file with location under `paths` and `file-path`
# Replace every `main` with the branch name (use find and replace all for convenience)

name: Update latexdiff pdf

on:
  push:
    branches:
    - main
    paths:
    - intro.tex
    - folder1/test.tex

jobs:
  latexdiff:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file-path: [intro.tex, folder1/test.tex]

    steps:
    - name: latexdiff for ${{ matrix.file-path }}
      uses: actions/checkout@v2

      # Install latexdiff
    - name: Install latexdiff
      run: |
        curl -o latexdiff.zip http://ctan.imsc.res.in/support/latexdiff.zip
        unzip latexdiff.zip
        cd latexdiff
        sudo make install
        cd ..

      # Save latest commit as new.tex and second latest commit as old.tex
    - name: Save commits into files
      run: |
        ls -a
        git log -n 1 --pretty=format:"%H" main ${{ matrix.file-path }} | xargs -I{} git show {}:${{ matrix.file-path }} > new.tex
        git log -n 1 --skip 1 --pretty=format:"%H" main ${{ matrix.file-path }} | xargs -I{} git show {}:${{ matrix.file-path }} > old.tex
        ls
      # Run latexdiff on old.tex and new.tex and save it as pdf
    - name: Run latexdiff
      run: |
        yes "" | latexdiff-vc --pdf old.tex new.tex

      # Create a pull request
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3.8.2
      with:
        delete-branch: true
        branch-suffix: short-commit-hash
        commit-message: Update ${{ matrix.file-path }} pdf
        title: Update ${{ matrix.file-path }} pdf
        body: |
            Update ${{ matrix.file-path }} pdf
